# Generated by Django 5.0.7 on 2024-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='compradoPor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
